PostCode/PostCode/Controllers/PostsController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PostCode.Models;
using PostCode.Repository;
using PostCode.Repository.Interface;

namespace PostCode.Controllers
{
    [ValidateInput(false)]
    public class PostsController : Controller
    {
        private readonly ICommentLikeRepository _commentLikeRepository;
        private readonly IPostRaitingRepository _postRaitingRepository;
        private readonly IPostRepository _postRepository;
        private readonly IUserRepository _userRepository;
        private readonly ICommentRepository _commentRepository;
        public PostsController(IPostRepository postRepository, IUserRepository userRepository,
            ICommentLikeRepository commentLikeRepository, IPostRaitingRepository postRaitingRepository,ICommentRepository commentRepository)
        {
            _commentLikeRepository = commentLikeRepository;
            _postRaitingRepository = postRaitingRepository;
            _postRepository = postRepository;
            _userRepository = userRepository;
            _commentRepository = commentRepository;
        }
        // GET: Posts
        public async Task<ActionResult> Index()
        {
            var posts = _postRepository.GetAll().Select(post => new Post()
            {
                Id =post.Id,
                Content = post.Content,
                Code = post.Code,
                Data = post.Data,
                User = post.User,
                Name = post.Name 
            });
            return View(posts);
        }

        // GET: Posts/Details
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var post = _postRepository.GetById(id);
            var postModel = new Post()
            {
                Id = post.Id,
                Code = post.Code,
                Content = post.Content,
                Data = post.Data,
                Name = post.Name,
                Comments = _commentRepository.FindBy(x=> x.PostId == post.Id).Select(com => new Comment()
                {
                    Id = com.Id,
                    Content = com.Content,
                    Data = com.Data,
                    User = _userRepository.GetById(com.UserId)
                }),
                User = _userRepository.GetById(post.UserId)

            };
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(postModel);
        }

        [Authorize]
        // GET: Posts/Create
        public ActionResult Create()
        {
            return View();
        }

        public void LikeComment(string commentId, int value)
        {
            if (ModelState.IsValid)
            {
                var commentLike = new CommentLike()
                {
                    Id = Guid.NewGuid().ToString(),
                    Value = value,
                    Comment = _commentRepository.GetById(commentId),
                    User = _userRepository.GetById(User.Identity.GetUserId())
                };
                _commentLikeRepository.Add(commentLike);
            }
        }
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public async Task<ActionResult> Create([Bind(Include = "Id,Content,Code,Data,Name,UserId")] Post post)
        {
            if (ModelState.IsValid)
            {
                post.Id = Guid.NewGuid().ToString();
                post.UserId = User.Identity.GetUserId();
                post.Data = DateTime.Now;
                _postRepository.Add(post);
                _postRepository.Save();
                return RedirectToAction("Index");
            }
            return View(post);
        }

         [Authorize]
        // GET: Posts/Edit
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
             
            Post post =_postRepository.GetById(id);
            if (post == null || (_userRepository.GetById(post.UserId).Id != User.Identity.GetUserId() && User.IsInRole("user")))
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // POST: Posts/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Content,Code,Data, Name, UserId")] Post post)
        {
            if(post == null||(_userRepository.GetById(post.UserId).Id != User.Identity.GetUserId() && User.IsInRole("user"))) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            if (ModelState.IsValid)
            {
                post.UserId = User.Identity.GetUserId();
                post.User = _userRepository.GetById(post.UserId);
                _postRepository.Edit(post);
                _postRepository.Save();
                return RedirectToAction("Index");
            }
            return View(post);
        }

        // GET: Posts/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = _postRepository.GetById(id);
            if (post == null || (_userRepository.GetById(post.UserId).Id != User.Identity.GetUserId() && User.IsInRole("user"))) return HttpNotFound();
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // POST: Posts/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            Post post = _postRepository.GetById(id);
            _postRepository.Delete(post);
            _postRepository.Save();
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpPost]
        public void AddComment(string postId, string content)
        {
            if (ModelState.IsValid)
            {
                Comment comment = new Comment();
                comment.Id = Guid.NewGuid().ToString();
                comment.UserId = User.Identity.GetUserId();
                comment.Content = content;
                comment.Data = DateTime.Now;
                comment.PostId = postId;

                _commentRepository.Add(comment);
                _commentRepository.Save();
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _postRepository.Dispose();
            }
        }
    }
}

PostCode/PostCode/Views/Posts/Create.cshtml
@model PostCode.Models.Post

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create Post</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                <textarea name="Content" data-provide="markdown" rows="10" id="Content" style="max-width: 100%"></textarea>
                @Html.ValidationMessageFor(model => model.Content, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                <textarea name="Code" style="max-width: 100%; width: 100%" rows="10"></textarea>
                @Html.ValidationMessageFor(model => model.Code, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<a href='@Url.Action("Index", "Posts")'>
    <input type='button' value='Back to List' class="btn btn-default" />
</a>

PostCode/PostCode/Views/Posts/Delete.cshtml
@model PostCode.Models.Post

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-1">
                @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-1" })
            </div>
            <div class="col-md-10">
                <textarea name="Content" id="Content" style="max-width: 100%;">@Html.DisplayFor(model => model.Content)</textarea>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-1" style="padding-top: 3%">
                @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-1" })
            </div>
            <div class="col-md-10" style="padding-top: 3%">
                <pre><code>@Html.DisplayFor(model => model.Code)</code></pre>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10" style="padding-left: 75%; width: 100%; padding-bottom: 5px">
                Created by @Html.DisplayFor(model => model.User.Email)
            </div>
            <div class="col-md-10" style="padding-left: 80%; width: 100%">
                @Html.DisplayFor(model => model.Data)
            </div>
        </div>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
            <a href='@Url.Action("Index", "Posts", new { id = Model.Id })'>
                <input type='button' value='Back to List' class="btn btn-default" />
            </a>
        </div>
    }
</div>
@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('pre code').each(function (i, e) {
                hljs.highlightBlock(e);
            });
        });
        $(document).ready(function() {
            $("#Content").markdown({
                autofocus: false,
                hiddenButtons: "",
                initialstate: "preview",
                fullscreen: false
            }).initialstate = "preview";
            $(".md-editor").attr("class", "");
        });
    </script>
}

PostCode/PostCode/Views/Posts/Details.cshtml
@model PostCode.Models.Post

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h2>@Html.DisplayFor(model => model.Name)</h2>
    <div class="col-md-3 col-lg-offset-9">
        <a href='@Url.Action("Edit", "Posts", new {id = Model.Id})'>
            <input type='button' value='Edit' class="btn btn-default"/>
        </a>
        <a href='@Url.Action("Delete", "Posts", new {id = Model.Id})'>
            <input type='button' value='Delete' class="btn btn-default"/>
        </a>
    </div>
    <hr/>
    <div hidden="" id="PostId">@Model.Id</div>
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-1" style="padding-top: 1%">
                @Html.LabelFor(model => model.Content, htmlAttributes: new {@class = "control-label col-md-1"})
            </div>
            <div class="col-md-10" style="padding-top: 1%">
                <textarea name="Content" id="Content" style="max-width: 100%;">@Html.DisplayFor(model => model.Content)</textarea>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-1" style="padding-top: 3%">
                @Html.LabelFor(model => model.Code, htmlAttributes: new {@class = "control-label col-md-1"})
            </div>
            <div class="col-md-10" style="padding-top: 3%">
                <pre><code>@Html.DisplayFor(model => model.Code)</code></pre>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10" style="padding-left: 74%; width: 100%; padding-bottom: 5px">
                Created by @Html.DisplayFor(model => model.User.Email)
            </div>
            <div class="col-md-10" style="padding-left: 78%; width: 100%">
                @Html.DisplayFor(model => model.Data)
            </div>
        </div>
        @foreach (var item in Model.Comments)
        {
            <div class="form-group">
                <div class="col-md-10 col-md-offset-1">
                    <div class=" panel panel-default">
                        <div class="panel-heading" id="name+@item.Id">
                            Commented by @item.User.Email
                            <div type="button" data-toggle="modal" data-target="#myModal" class="col-md-push-9 glyphicon glyphicon-pencil" id="@item.Id" onclick=" EditComment(this.id) "></div>
                        </div>
                        <div class="panel-body" id="cont+@item.Id">@item.Content</div>
                    </div>
                </div>
            </div>
        }
        <div class="modal fade bs-example-modal-lg" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header" id="commentName"></div>
                    <div class="modal-body" id="commentContent">
                        <textarea style="max-width: 100%; width: 100%; resize: none; border-color: #dddddd; border-radius: 4px; padding: 15px" wrap="soft" rows="5"></textarea>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary">Save changes</button>
                        <button type="button" class="btn btn-danger">Delete</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10 col-md-offset-1">
                <textarea id="Comment" style="max-width: 100%; width: 100%; resize: none; border-color: #dddddd; border-radius: 4px; padding: 15px" wrap="soft" rows="5"></textarea>
            </div>
        </div>
        <a style="padding-left: 83%">
            <input id="CommentBtn" type='button' value='Comment' class="btn btn-default"/>
        </a>
        <hr/>
        <a href='@Url.Action("Index", "Posts", new {id = Model.Id})'>
            <input type='button' value='Back to List' class="btn btn-default"/>
        </a>
    </div>
</div>


@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('pre code').each(function (i, e) {
                hljs.highlightBlock(e);
            });
        });

        $(document).ready(function () {
            $('#Content').markdown({
                autofocus: false,
                hiddenButtons: "",
                initialstate: "preview",
                fullscreen: false
            }).initialstate = "preview";
            $(".md-editor").attr("class", "");
        });

        var getPostId = document.getElementById("PostId").innerHTML;


        $(document).ready(function () {

            $('#CommentBtn').on('click', function () {
                var getContent = document.getElementById("Comment").value;
                $.ajax({
                    url: '/Posts/AddComment',
                    settings: {
                        type: 'POST'
                    },
                    type: 'POST',
                    data: {
                        'PostId': getPostId,
                        'Content': getContent
                    }
                });
            });
        });
    </script>
}

PostCode/PostCode/Views/Posts/Edit.cshtml
@model PostCode.Models.Post

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PostCode/PostCode/Views/Posts/Index.cshtml
@model IEnumerable<PostCode.Models.Post>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>All Posts</h2>

<table class="table">
@foreach (var item in Model) {
    <tr>
        <td style="width: 100px; vertical-align: middle">
            <div style="text-align: center">Rating</div>
        </td>
        <td style="vertical-align: middle">
            <div class="row">
                <div class="col-md-10" style="text-align: left">
                   <h4> @Html.ActionLink(item.Name, "Details", new { id = item.Id })</h4>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 col-md-offset-8" style="text-align:right">Created by @Html.DisplayFor(modelItem => item.User.Email))</div>
                <div class="col-md-4 col-md-offset-8" style="text-align:right">at @Html.DisplayFor(modelItem => item.Data)</div>
            </div>
        </td>
    </tr>
}
</table>